# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: true

cran: https://cran.rstudio.com

# until generics is finalized
warnings_are_errors: false

r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - devel


matrix:
  allow_failures:
    - r: 3.3       # inum      install failure (seg fault)
    - r: 3.2       # partykit  install failure (libcoin needs >= 3.4.0)
    - r: 3.4       # mvtnorm   requires >= 3.5.0

r_binary_packages:
  - RCurl
  - dplyr
  - glue
  - magrittr
  - stringi
  - stringr
  - munsell
  - rlang
  - reshape2
  - scales
  - tibble
  - ggplot2
  - Rcpp
  - RcppEigen
  - BH
  - glmnet
  - earth
  - sparklyr
  - flexsurv
  - ranger
  - randomforest
  - xgboost
  - C50


cache:
  packages: false
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

env:
  global:
  - KERAS_BACKEND="tensorflow"
  - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      g++-6

before_script:
  - python -m pip install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - python -m pip install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'


before_install:
  - sudo apt-get -y install libnlopt-dev
  - sudo apt-get update
  - sudo apt-get -y install python3
  - mkdir -p ~/.R && echo "CXX14=g++-6" > ~/.R/Makevars
  - echo "CXX14FLAGS += -fPIC" >> ~/.R/Makevars


after_success:
  - Rscript -e 'covr::codecov()'

